### ISSUE TITLE
Python 应该怎么办呢？

### ISSUE THREAD

**Issue by yunsii** [ANBUZHIDAO/myFirefoxDriver#1]
还在摸索中~~~

**Comment by ANBUZHIDAO** [comment]
已更新。添加了Python的实现，没大量使用过，可能会有问题。

Selenium的架构可以参考 http://blog.csdn.net/wwwqjpcom/article/details/51232302
然后我最近试了一下Python的。
简单自测OK。如下：

![python_myfirefoxdriver](https://user-images.githubusercontent.com/25934111/36062624-fa221364-0eaa-11e8-8165-777ae32092d7.JPG)

**Comment by yunsii** [comment]
from webdriver import myFirefox
import pickle

f = open("params.data", 'rb')
params = pickle.load(f)
print(params)

browser = myFirefox.myWebDriver(service_url=params["server_url"],
    session_id=params["session_id"])

您好，这个myFirefox是什么操作？没搞懂，运行到这里就懵了

**Comment by ANBUZHIDAO** [comment]
你把 https://github.com/ANBUZHIDAO/myFirefoxDriver/tree/master/python 下载下来
运行里面的  
testGecko.py  testMyFirefox2.py 试一下。

myFirefox 是from webdriver import myFirefox 时，从webdriver目录导入的。

我的myFirefox实现是在 https://github.com/ANBUZHIDAO/myFirefoxDriver/tree/master/python下面的webdriver目录里的myFirefox.py。

**Comment by yunsii** [comment]
成是成功了，大佬自学一下就这么厉害了。看来我还有很长的路要走啊。
 
我这先去把myFirefox搞懂先_(:3J∠)_
